'use server';

import { revalidatePath } from 'next/cache';
import { sql, and, eq, desc } from 'drizzle-orm';
import { db, withActor, emailMessages } from '@antagna/db';
import { AiBudgetError } from '@antagna/ai';
import { requirePermissionAction } from '@/lib/authz';
import { writeActivity } from '@/lib/activity';
import { createClientQuick } from '@/app/clients/actions';
import { extractEmail } from '@/lib/email-intel/extract';

/** Map extractEmail's internal English codes to user-facing Arabic. */
function reanalyzeErrorAr(code?: string): string {
  switch (code) {
    case 'junk_category': return 'المحادثة مصنّفة كغير تجارية (تسويق/إشعار)';
    case 'body_too_short': return 'لا يوجد نص كافٍ للتحليل';
    case 'not_inbound': return 'آخر رسالة ليست واردة';
    case 'not_found': return 'الرسالة غير موجودة';
    case 'truncated_response': return 'النتيجة طويلة وتم اقتطاعها — حاول مجددًا';
    case 'json_parse_failed': return 'تعذّر قراءة نتيجة التحليل، حاول مجددًا';
    default: return 'فشل التحليل';
  }
}

const STAGES = new Set([
  'lead', 'brief', 'quoted', 'approved', 'planning', 'shooting', 'editing', 'review', 'delivered',
]);

export type ImportInput = {
  threadId: string;
  title: string;
  titleAr?: string | null;
  clientName: string;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  stage: string;
  quoteNumber?: string | null;
  deliveryDue?: string | null;
  shootStart?: string | null;
  isAbuLukaContent?: boolean;
};

/**
 * Confirm one email-sourced candidate → create/link client, create the project,
 * create the primary contact, and link the source thread. Everything in actor
 * scope so the audit trail sees who did it.
 */
export async function importEmailProject(
  input: ImportInput,
): Promise<{ ok: boolean; projectId?: string; error?: string }> {
  const actorId = await requirePermissionAction('project.create');
  const title = input.title?.trim();
  const isAbuLuka = input.isAbuLukaContent === true;
  // Abu Luka content still needs a client (client_id is NOT NULL) — default the
  // entity to "أبو لوكا" when none was given.
  const clientName = input.clientName?.trim() || (isAbuLuka ? 'أبو لوكا' : '');
  if (!title) return { ok: false, error: 'اسم المشروع مطلوب' };
  if (!clientName) return { ok: false, error: isAbuLuka ? 'الجهة مطلوبة' : 'اسم العميل مطلوب' };
  const stage = STAGES.has(input.stage) ? input.stage : 'brief';

  // Find-or-create the client by name.
  let clientId: string;
  const found = (await db.execute(sql`
    SELECT id::text AS id FROM clients
    WHERE archived_at IS NULL AND (
      lower(name_en) = lower(${clientName}) OR lower(name_ar) = lower(${clientName})
      OR lower(name_en) LIKE ${'%' + clientName.toLowerCase() + '%'}
      OR lower(name_ar) LIKE ${'%' + clientName.toLowerCase() + '%'})
    LIMIT 1`)) as unknown as Array<{ id: string }>;
  if (found[0]) {
    clientId = found[0].id;
  } else {
    const c = await createClientQuick({ nameAr: clientName, nameEn: clientName, clientType: 'brand' });
    if (!c.ok) return { ok: false, error: c.error };
    clientId = c.client.id;
  }

  // Create the project (code is DB-generated by trigger).
  const projId = await withActor(actorId, async (tx) => {
    const res = await tx.execute<{ id: string }>(sql`
      INSERT INTO projects (
        title, title_ar, client_id, project_type, stage, brief_received_at,
        dafterah_quote_number, is_abu_luka_content,
        delivery_due_at, shoot_starts_at, created_by
      ) VALUES (
        ${title}, ${input.titleAr ?? null}, ${clientId}::uuid,
        'content_creation'::project_type, ${stage}::project_stage, now(),
        ${input.quoteNumber?.trim() || null}, ${isAbuLuka},
        ${input.deliveryDue ? sql`${input.deliveryDue}::timestamptz` : sql`NULL`},
        ${input.shootStart ? sql`${input.shootStart}::timestamptz` : sql`NULL`},
        ${actorId}::uuid
      ) RETURNING id::text AS id`);
    return (res as unknown as Array<{ id: string }>)[0]?.id ?? null;
  });
  if (!projId) return { ok: false, error: 'فشل إنشاء المشروع' };

  // Primary contact (best-effort).
  if (input.contactName?.trim()) {
    try {
      await withActor(actorId, async (tx) => {
        const cr = await tx.execute<{ id: string }>(sql`
          INSERT INTO contacts (client_id, full_name, is_primary)
          VALUES (${clientId}::uuid, ${input.contactName!.trim()}, true)
          RETURNING id::text AS id`);
        const contactId = (cr as unknown as Array<{ id: string }>)[0]?.id;
        if (contactId && input.contactEmail?.trim()) {
          await tx.execute(sql`
            INSERT INTO contact_methods (contact_id, method_type, value, normalized_value, is_primary)
            VALUES (${contactId}::uuid, 'email'::contact_method_type, ${input.contactEmail.trim()}, lower(${input.contactEmail.trim()}), true)
            ON CONFLICT DO NOTHING`);
        }
        if (contactId && input.contactPhone?.trim()) {
          const phone = input.contactPhone.trim();
          await tx.execute(sql`
            INSERT INTO contact_methods (contact_id, method_type, value, normalized_value, is_primary)
            VALUES (${contactId}::uuid, 'phone'::contact_method_type, ${phone}, regexp_replace(${phone}, '[^0-9+]', '', 'g'), false)
            ON CONFLICT DO NOTHING`);
        }
      });
    } catch (e) {
      console.error('[intake contact]', e);
    }
  }

  // Link the source email thread to the new project + client.
  await withActor(actorId, (tx) =>
    tx.execute(sql`
      UPDATE email_threads
      SET project_id = ${projId}::uuid, client_id = COALESCE(client_id, ${clientId}::uuid), updated_at = now()
      WHERE id = ${input.threadId}::uuid`),
  );

  await writeActivity({
    actorId,
    entityType: 'project',
    entityId: projId,
    action: 'project_created',
    summaryAr: `أُنشئ مشروع من البريد: ${title}`,
    summaryEn: `Project imported from email: ${title}`,
  });

  revalidatePath('/intake');
  revalidatePath('/projects');
  revalidatePath('/crm');
  return { ok: true, projectId: projId };
}

/**
 * Re-run deep extraction on a thread's latest inbound message with the current
 * (richer) extractor — populates brief/scope/key-details/missing-info/next-step.
 */
export async function reanalyzeCandidate(
  threadId: string,
): Promise<{ ok: boolean; error?: string }> {
  const actorId = await requirePermissionAction('project.create');
  const [latest] = await db
    .select({ id: emailMessages.id })
    .from(emailMessages)
    .where(and(eq(emailMessages.threadId, threadId), eq(emailMessages.direction, 'inbound')))
    .orderBy(desc(emailMessages.sentAt))
    .limit(1);
  if (!latest) return { ok: false, error: 'لا توجد رسالة واردة في هذه المحادثة' };

  // Cheap anti-spam: don't re-burn Sonnet tokens if this exact message was
  // analyzed in the last 60s.
  const recent = (await db.execute(sql`
    SELECT 1 FROM email_extractions
    WHERE message_id = ${latest.id}::uuid AND extracted_at > now() - interval '60 seconds'
    LIMIT 1`)) as unknown as Array<unknown>;
  if (recent.length) {
    return { ok: false, error: 'تم التحليل للتوّ — انتظر دقيقة قبل إعادة المحاولة' };
  }

  // Pass the actor so per-user AI budget caps engage; map a budget/error throw
  // to an Arabic message instead of letting the server action reject (which
  // would hang the button).
  let res: Awaited<ReturnType<typeof extractEmail>>;
  try {
    res = await extractEmail(latest.id, { userId: actorId });
  } catch (e) {
    return { ok: false, error: e instanceof AiBudgetError ? e.message : 'فشل التحليل' };
  }
  if (!res.ok) return { ok: false, error: reanalyzeErrorAr(res.error) };
  revalidatePath('/intake');
  return { ok: true };
}

/** Hide a candidate from the intake list (stored in system_settings). */
export async function dismissCandidate(threadId: string): Promise<{ ok: boolean }> {
  await requirePermissionAction('project.create');
  await db.execute(sql`
    INSERT INTO system_settings (key, value, updated_at)
    VALUES ('intake_dismissed', ${JSON.stringify([threadId])}::jsonb, now())
    ON CONFLICT (key) DO UPDATE
      SET value = (
        SELECT to_jsonb(array(SELECT DISTINCT jsonb_array_elements_text(system_settings.value || ${JSON.stringify([threadId])}::jsonb)))
      ), updated_at = now()`);
  revalidatePath('/intake');
  return { ok: true };
}
