'use server';

import { revalidatePath } from 'next/cache';
import { sql } from 'drizzle-orm';
import { db, withActor } from '@antagna/db';
import { requirePermissionAction } from '@/lib/authz';
import { writeActivity } from '@/lib/activity';
import { createClientQuick } from '@/app/clients/actions';

const STAGES = new Set([
  'lead', 'brief', 'quoted', 'approved', 'planning', 'shooting', 'editing', 'review', 'delivered',
]);

export type ImportInput = {
  threadId: string;
  title: string;
  titleAr?: string | null;
  clientName: string;
  contactName?: string | null;
  contactEmail?: string | null;
  stage: string;
  quoteNumber?: string | null;
  deliveryDue?: string | null;
  shootStart?: string | null;
};

/**
 * Confirm one email-sourced candidate → create/link client, create the project,
 * create the primary contact, and link the source thread. Everything in actor
 * scope so the audit trail sees who did it.
 */
export async function importEmailProject(
  input: ImportInput,
): Promise<{ ok: boolean; projectId?: string; error?: string }> {
  const actorId = await requirePermissionAction('project.create');
  const title = input.title?.trim();
  const clientName = input.clientName?.trim();
  if (!title) return { ok: false, error: 'اسم المشروع مطلوب' };
  if (!clientName) return { ok: false, error: 'اسم العميل مطلوب' };
  const stage = STAGES.has(input.stage) ? input.stage : 'brief';

  // Find-or-create the client by name.
  let clientId: string;
  const found = (await db.execute(sql`
    SELECT id::text AS id FROM clients
    WHERE archived_at IS NULL AND (
      lower(name_en) = lower(${clientName}) OR lower(name_ar) = lower(${clientName})
      OR lower(name_en) LIKE ${'%' + clientName.toLowerCase() + '%'}
      OR lower(name_ar) LIKE ${'%' + clientName.toLowerCase() + '%'})
    LIMIT 1`)) as unknown as Array<{ id: string }>;
  if (found[0]) {
    clientId = found[0].id;
  } else {
    const c = await createClientQuick({ nameAr: clientName, nameEn: clientName, clientType: 'brand' });
    if (!c.ok) return { ok: false, error: c.error };
    clientId = c.client.id;
  }

  // Create the project (code is DB-generated by trigger).
  const projId = await withActor(actorId, async (tx) => {
    const res = await tx.execute<{ id: string }>(sql`
      INSERT INTO projects (
        title, title_ar, client_id, project_type, stage, brief_received_at,
        dafterah_quote_number, delivery_due_at, shoot_starts_at, created_by
      ) VALUES (
        ${title}, ${input.titleAr ?? null}, ${clientId}::uuid,
        'content_creation'::project_type, ${stage}::project_stage, now(),
        ${input.quoteNumber?.trim() || null},
        ${input.deliveryDue ? sql`${input.deliveryDue}::timestamptz` : sql`NULL`},
        ${input.shootStart ? sql`${input.shootStart}::timestamptz` : sql`NULL`},
        ${actorId}::uuid
      ) RETURNING id::text AS id`);
    return (res as unknown as Array<{ id: string }>)[0]?.id ?? null;
  });
  if (!projId) return { ok: false, error: 'فشل إنشاء المشروع' };

  // Primary contact (best-effort).
  if (input.contactName?.trim()) {
    try {
      await withActor(actorId, async (tx) => {
        const cr = await tx.execute<{ id: string }>(sql`
          INSERT INTO contacts (client_id, full_name, is_primary)
          VALUES (${clientId}::uuid, ${input.contactName!.trim()}, true)
          RETURNING id::text AS id`);
        const contactId = (cr as unknown as Array<{ id: string }>)[0]?.id;
        if (contactId && input.contactEmail?.trim()) {
          await tx.execute(sql`
            INSERT INTO contact_methods (contact_id, method_type, value, normalized_value, is_primary)
            VALUES (${contactId}::uuid, 'email'::contact_method_type, ${input.contactEmail.trim()}, lower(${input.contactEmail.trim()}), true)
            ON CONFLICT DO NOTHING`);
        }
      });
    } catch (e) {
      console.error('[intake contact]', e);
    }
  }

  // Link the source email thread to the new project + client.
  await withActor(actorId, (tx) =>
    tx.execute(sql`
      UPDATE email_threads
      SET project_id = ${projId}::uuid, client_id = COALESCE(client_id, ${clientId}::uuid), updated_at = now()
      WHERE id = ${input.threadId}::uuid`),
  );

  await writeActivity({
    actorId,
    entityType: 'project',
    entityId: projId,
    action: 'project_created',
    summaryAr: `أُنشئ مشروع من البريد: ${title}`,
    summaryEn: `Project imported from email: ${title}`,
  });

  revalidatePath('/intake');
  revalidatePath('/projects');
  revalidatePath('/crm');
  return { ok: true, projectId: projId };
}

/** Hide a candidate from the intake list (stored in system_settings). */
export async function dismissCandidate(threadId: string): Promise<{ ok: boolean }> {
  await requirePermissionAction('project.create');
  await db.execute(sql`
    INSERT INTO system_settings (key, value, updated_at)
    VALUES ('intake_dismissed', ${JSON.stringify([threadId])}::jsonb, now())
    ON CONFLICT (key) DO UPDATE
      SET value = (
        SELECT to_jsonb(array(SELECT DISTINCT jsonb_array_elements_text(system_settings.value || ${JSON.stringify([threadId])}::jsonb)))
      ), updated_at = now()`);
  revalidatePath('/intake');
  return { ok: true };
}
