// packages/db/src/schema/safe_views.ts
//
// Read-only Drizzle handles for the Sprint 0 v_*_safe masking views (migration
// 051). DDL is owned by the SQL migration, NOT drizzle-kit — hence pgView(...).
// .existing(). Columns/order MUST mirror the migration's SELECT. All masked
// columns are nullable at runtime even when the base column is NOT NULL.
import { pgView, uuid, text, boolean, integer, numeric, timestamp, jsonb } from 'drizzle-orm/pg-core';

export const vProjectsSafe = pgView('v_projects_safe', {
  id: uuid('id'),
  code: text('code'),
  title: text('title'),
  titleAr: text('title_ar'),
  description: text('description'),
  projectType: text('project_type'),
  stage: text('stage'),
  clientId: uuid('client_id'),
  agencyId: uuid('agency_id'),
  agencyContactId: uuid('agency_contact_id'),
  primaryContactId: uuid('primary_contact_id'),
  accountManagerId: uuid('account_manager_id'),
  projectManagerId: uuid('project_manager_id'),
  productionManagerId: uuid('production_manager_id'),
  locationId: uuid('location_id'),
  briefReceivedAt: timestamp('brief_received_at', { withTimezone: true }),
  quotedAt: timestamp('quoted_at', { withTimezone: true }),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  shootStartsAt: timestamp('shoot_starts_at', { withTimezone: true }),
  shootEndsAt: timestamp('shoot_ends_at', { withTimezone: true }),
  deliveryDueAt: timestamp('delivery_due_at', { withTimezone: true }),
  deliveredAt: timestamp('delivered_at', { withTimezone: true }),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  lostReason: text('lost_reason'),
  isAbuLukaContent: boolean('is_abu_luka_content'),
  contractedValueSar: numeric('contracted_value_sar'),
  aiStatusParagraph: text('ai_status_paragraph'),
  aiRiskLevel: text('ai_risk_level'),
  aiNextAction: text('ai_next_action'),
  aiAnalyzedAt: timestamp('ai_analyzed_at', { withTimezone: true }),
  driveFolderUrl: text('drive_folder_url'),
  driveFolderId: text('drive_folder_id'),
  calendarEventId: text('calendar_event_id'),
  dafterahQuoteNumber: text('dafterah_quote_number'),
  dafterahInvoiceNumber: text('dafterah_invoice_number'),
  dafterahPoNumber: text('dafterah_po_number'),
  defaultApprovalFlow: jsonb('default_approval_flow'),
  recurrenceRule: text('recurrence_rule'),
  recurrenceParentId: uuid('recurrence_parent_id'),
  nextOccurrenceAt: timestamp('next_occurrence_at', { withTimezone: true }),
  customFields: jsonb('custom_fields'),
  notes: text('notes'),
  postMortemNotes: text('post_mortem_notes'),
  createdBy: uuid('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
}).existing();

export const vClientsSafe = pgView('v_clients_safe', {
  id: uuid('id'),
  code: text('code'),
  nameAr: text('name_ar'),
  nameEn: text('name_en'),
  legalName: text('legal_name'),
  vatNumber: text('vat_number'),
  crNumber: text('cr_number'),
  clientType: text('client_type'),
  isAgency: boolean('is_agency'),
  industry: text('industry'),
  country: text('country'),
  city: text('city'),
  addressLines: text('address_lines'),
  websiteUrl: text('website_url'),
  logoUrl: text('logo_url'),
  defaultPaymentTermsKey: text('default_payment_terms_key'),
  averagePaymentDays: integer('average_payment_days'),
  trustScore: integer('trust_score'),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  notes: text('notes'),
  customFields: jsonb('custom_fields'),
  createdBy: uuid('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
}).existing();

export const vContactsSafe = pgView('v_contacts_safe', {
  id: uuid('id'),
  clientId: uuid('client_id'),
  fullName: text('full_name'),
  fullNameAr: text('full_name_ar'),
  jobTitle: text('job_title'),
  jobTitleAr: text('job_title_ar'),
  department: text('department'),
  isPrimary: boolean('is_primary'),
  isDecisionMaker: boolean('is_decision_maker'),
  preferredLanguage: text('preferred_language'),
  notes: text('notes'),
  customFields: jsonb('custom_fields'),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
}).existing();

export const vEquipmentSafe = pgView('v_equipment_safe', {
  id: uuid('id'),
  code: text('code'),
  groupId: uuid('group_id'),
  category: text('category'),
  manufacturer: text('manufacturer'),
  model: text('model'),
  modelNameAr: text('model_name_ar'),
  serialNumber: text('serial_number'),
  trackingMode: text('tracking_mode'),
  quantityTotal: integer('quantity_total'),
  status: text('status'),
  currentLocation: text('current_location'),
  purchaseDate: text('purchase_date'),
  purchasePriceSar: numeric('purchase_price_sar'),
  insuranceValueSar: numeric('insurance_value_sar'),
  warrantyUntil: text('warranty_until'),
  depreciationMethod: text('depreciation_method'),
  usefulLifeMonths: integer('useful_life_months'),
  currentBookValueSar: numeric('current_book_value_sar'),
  requiresCharging: boolean('requires_charging'),
  lastChargedAt: timestamp('last_charged_at', { withTimezone: true }),
  photoUrl: text('photo_url'),
  manualUrl: text('manual_url'),
  specs: jsonb('specs'),
  isKitItem: boolean('is_kit_item'),
  parentKitId: uuid('parent_kit_id'),
  notes: text('notes'),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
}).existing();

export const vEmailThreadsSafe = pgView('v_email_threads_safe', {
  id: uuid('id'),
  gmailThreadId: text('gmail_thread_id'),
  subject: text('subject'),
  projectId: uuid('project_id'),
  leadId: uuid('lead_id'),
  clientId: uuid('client_id'),
  primaryContactId: uuid('primary_contact_id'),
  assignedProfileId: uuid('assigned_profile_id'),
  status: text('status'),
  messageCount: integer('message_count'),
  lastMessageAt: timestamp('last_message_at', { withTimezone: true }),
  lastInboundAt: timestamp('last_inbound_at', { withTimezone: true }),
  lastOutboundAt: timestamp('last_outbound_at', { withTimezone: true }),
  aiSummary: text('ai_summary'),
  aiSummaryUpdatedAt: timestamp('ai_summary_updated_at', { withTimezone: true }),
  aiTopicTags: text('ai_topic_tags').array(),
  createdAt: timestamp('created_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
}).existing();

export const vTeamSafe = pgView('v_team_safe', {
  id: uuid('id'),
  authUserId: uuid('auth_user_id'),
  displayName: text('display_name'),
  displayNameEn: text('display_name_en'),
  legalName: text('legal_name'),
  role: text('role'),
  positionKey: text('position_key'),
  status: text('status'),
  departmentId: uuid('department_id'),
  reportsToId: uuid('reports_to_id'),
  avatarUrl: text('avatar_url'),
  email: text('email'),
  phoneE164: text('phone_e164'),
  whatsappE164: text('whatsapp_e164'),
  uiLanguage: text('ui_language'),
  timezone: text('timezone'),
  monthlySalary: integer('monthly_salary'),
  monthlySalaryCurrency: text('monthly_salary_currency'),
  createdAt: timestamp('created_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
}).existing();
